targets:
  $default:
    builders:
      menthe_generator:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*

builders:
  menthe_generator:
    import: "package:menthe_generator/builder.dart"
    builder_factories: ["mentheBuilder"]
    build_extensions: {".dart": [".menthe.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]