name: menthe_generator
description: menthe code generator
repository: https://github.com/rIIh/menthe

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.0.0
  analyzer: ^5.0.0
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  collection: ^1.0.0
  dart_style: ^2.0.0
  menthe_annotation: ^2.0.0
  source_gen: ^1.0.0
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.7
  build_verify: ^3.0.0
  riverpod: ^2.3.0
  test: ^1.21.0